// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFOaNOiiVE7zBI0sqQ4JSWbEuh5i0G4Yw',
    appId: '1:1040301841098:web:3656bb80d500193524b233',
    messagingSenderId: '1040301841098',
    projectId: 'device-streaming-150e9374',
    authDomain: 'device-streaming-150e9374.firebaseapp.com',
    storageBucket: 'device-streaming-150e9374.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9piMRK2RWRxZ-s1w6Gj0TfglqHo2WzHo',
    appId: '1:1040301841098:android:e2894c4e2e9067f024b233',
    messagingSenderId: '1040301841098',
    projectId: 'device-streaming-150e9374',
    storageBucket: 'device-streaming-150e9374.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdFvhHsn78_09y-u_BQuXDkdgcgWtsefk',
    appId: '1:1040301841098:ios:aa275d870099206824b233',
    messagingSenderId: '1040301841098',
    projectId: 'device-streaming-150e9374',
    storageBucket: 'device-streaming-150e9374.firebasestorage.app',
    iosBundleId: 'com.example.pomo2Tracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdFvhHsn78_09y-u_BQuXDkdgcgWtsefk',
    appId: '1:1040301841098:ios:aa275d870099206824b233',
    messagingSenderId: '1040301841098',
    projectId: 'device-streaming-150e9374',
    storageBucket: 'device-streaming-150e9374.firebasestorage.app',
    iosBundleId: 'com.example.pomo2Tracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFOaNOiiVE7zBI0sqQ4JSWbEuh5i0G4Yw',
    appId: '1:1040301841098:web:34b0bf073d71a37d24b233',
    messagingSenderId: '1040301841098',
    projectId: 'device-streaming-150e9374',
    authDomain: 'device-streaming-150e9374.firebaseapp.com',
    storageBucket: 'device-streaming-150e9374.firebasestorage.app',
  );

}